'use client';

import { FormEvent, useState } from 'react';
import { invoiceRequestSchema } from '@/lib/validations';
import { formatInvoiceNumber } from '@/lib/invoices';

export default function InvoicePage() {
  const [message, setMessage] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const raw = Object.fromEntries(new FormData(event.currentTarget)); const result = invoiceRequestSchema.safeParse({ firstName: raw.firstname, lastName: raw.lastname, email: raw.email, phone: raw.phone, address: raw.billingaddress, city: raw.city, postalCode: raw.postalcode, company: raw.company, taxId: raw.taxvatnumber, purchaseOrder: raw.ponumber, notes: raw.notes }); setMessage(result.success ? `Request recorded. Your draft reference is ${formatInvoiceNumber(1)}.` : 'Please complete the required fields with a valid email and contact number.'); };
  return <main className="page-shell"><header><p className="eyebrow">Invoice checkout</p><h1>Purchase the way your business works.</h1><p>Use this path for contractor, company and purchase-order orders. Card information is never collected directly in this application.</p></header><div className="invoice-grid"><form className="form-card" onSubmit={submit}><h2>Request an invoice</h2><div className="form-grid">{['First name', 'Last name', 'Company', 'Email', 'Phone', 'Billing address', 'Shipping address', 'City', 'Postal code', 'Tax/VAT number', 'PO number'].map((label) => <label key={label} className={label.includes('address') ? 'wide' : ''}>{label}{['First name','Last name','Email','Phone','Billing address','Shipping address','City','Postal code'].includes(label) && ' *'}<input required={['First name','Last name','Email','Phone','Billing address','Shipping address','City','Postal code'].includes(label)} name={label.toLowerCase().replace(/[^a-z]/g, '')} type={label === 'Email' ? 'email' : 'text'}/></label>)}<label className="wide">Order notes<textarea name="notes" rows={4}/></label></div><button className="button dark" type="submit" style={{ marginTop: 22 }}>Request invoice</button>{message && <p className="notice" style={{ marginTop: 18 }}>{message}</p>}</form><aside className="aside-card"><h2>What happens next</h2><ol><li>We verify products, delivery address and final pricing.</li><li>We issue an invoice with items, taxes, shipping and due date.</li><li>A secure payment link is attached after approval.</li></ol><p className="notice">Invoice number generation is transaction-scoped in the production data layer to prevent duplicates.</p></aside></div></main>;
}
